export const SET_CANDIDATES = 'SET_CANDIDATES'
export const SET_LOADING_CANDIDATES = 'SET_LOADING_CANDIDATES'
export const SET_CANDIDATE_DETAILS = 'SET_CANDIDATE_DETAILS'
export const SET_LOADING_CANDIDATE_DETAILS = 'SET_LOADING_CANDIDATE_DETAILS'
